version: "3"
services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_USER: ${MYSQL_USER_BLIND_SQL}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD_BLIND_SQL}
            MYSQL_ROOT_PASSWORD: an
            MYSQL_DATABASE: ${BLIND_SQL}
        volumes:
            - ./db:/var/lib/mysql
        ports:
            - "${PORTSQL_BLIND_SQL}:3306"
    app:
        build: .
        restart: on-failure
        links:
            - db:database
        depends_on: 
            - db
        ports:
            - "${PORT_BLIND_SQL}:${PORT_BLIND_SQL}"