version: "3"
services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: an
            MYSQL_DATABASE: ${BABY_SQL}
        volumes:
            - ./db:/var/lib/mysql
        ports:
            - "${PORTSQL_BABY_SQL}:3306"
    app:
        build: .
        restart: on-failure
        links:
            - db:database
        depends_on: 
            - db
        ports:
            - "${PORT_BABY_SQL}:${PORT_BABY_SQL}"